package io.violabs.kotlinliquibase.domain

import io.violabs.konstellation.metaDsl.annotation.GeneratedDsl

@GeneratedDsl(withListGroup = true)
data class ChangeSet(
    /**
     * Specifies an alpha-numeric identifier.
     *
     * Note: If there are zeros in the id, it is best practice to put quotes around the id, such as "1.10".
     * This allows all characters to be retained.
     */
    val id: String,
    val changes: List<Change>,
    /**
     * Specifies the creator of the changeset.
     * Must be non-empty if the global argument strict is true.
     * Can be empty only if strict is false.
     */
    val author: String? = null,
    /**
     * Stores dates, versions, or any other string of value without using remarks (comments) attributes.
     */
    val created: String? = null,
    /**
     * Specifies the changeset contexts to match.
     * Contexts are tags you can add to changesets to control which changesets will be
     * executed in any particular migration run.
     */
    val context: String? = null,
    /**
     * Specifies which database type(s) a changeset is to be used for.
     * See valid database type names on dbms. Separate multiple databases with commas.
     * Specify that a changeset is not applicable to a particular database type by prefixing with !.
     * The keywords all and none are also available.
     */
    val dbms: String? = null,
    /**
     *
     * Defines whether a database migration will fail if an error occurs while executing the changeset.
     * Default: true.
     */
    val failOnError: Boolean? = null,
    /**
     * Tells Liquibase to treat a particular changeset as if it does not exist.
     * Default: false. Since 3.6 (XML/YAML/JSON). Since 4.19.0 (SQL).
     */
    val ignore: Boolean? = null,
    /**
     * Specifies the changeset labels to match.
     * Labels are tags you can add to changesets to control which changesets will be executed
     * in any migration run.
     */
    val labels: String? = null,
    /**
     * Overrides the file name and path when creating the unique identifier of changesets.
     * It is required when you want to move or rename changelogs.
     */
    val logicalFilePath: String? = null,
    /**
     * Controls how object names are quoted in the SQL files generated by Liquibase and used in calls to the database.
     * Default: LEGACY
     *
     * LEGACY – The default value. Does not quote objects unless the database specifies that they must be quoted,
     *          usually including reserved words and names with hyphens. In PostgreSQL databases, mixed-case names
     *          will also be quoted.
     * QUOTE_ALL_OBJECTS – Every object gets quoted. For example, person becomes "person".
     * QUOTE_ONLY_RESERVED_WORDS – The same logic as LEGACY, but without mixed-case objects in PostgreSQL databases.
     * Not supported with Formatted Mongo.
     */
    val objectQuotingStrategy: ObjectQuotingStrategy? = null,
    /**
     * Controls what Liquibase does when a changeset fails validation.
     * Values are HALT and MARK_RAN.
     * Default: HALT.
     */
    val onValidationFail: ValidationFailBehavior? = null,
    /**
     * Executes the changeset on every run, even if it has been run before.
     * Default: false.
     */
    val runAlways: Boolean? = null,
    /**
     * Specifies whether the changeset can be run as a single transaction (if possible).
     * Default: true. Since 1.9.
     *
     * Warning: If runInTransaction is set to false and an error occurs part way through
     * running a changeset that contains multiple statements, the Liquibase DATABASECHANGELOG
     * table will be left in an invalid state.
     */
    val runInTransaction: Boolean? = null,
    /**
     * Executes the changeset when you create it and each time it changes.
     * Default: false.
     */
    val runOnChange: Boolean? = null,
    /**
     * Specifies whether a changeset should be run before or after all other changesets instead of
     * running it sequentially based on its order in the changelog.
     * Valid values are first and last. It is typically used when you want a changeset to be always
     * executed after everything else but don’t want to keep moving it to the end of the changelog.
     * Setting the runOrder to last will automatically move the changeset to the final place in
     * the changeset run order. Since 3.5
     * Note: runOrder is not supported in formatted SQL changelogs.
     */
    val runOrder: RunOrder? = null,
    /**
     *
     * Specifies a native executor to run your SQL
     * (jdbc, mongosh, psql, sqlcmd, sqlplus, or a custom executor).
     * Default: jdbc.
     */
    val runWith: RunWithExecutor? = null,
    /**
     * Specifies a spool file to send output to when you deploy a particular changeset.
     */
    val runWithSpoolFile: String? = null,
    /**
     * Preconditions required to execute the changelog.
     * If global, must be passed before the changeset is run.
     * Preconditions are typically used for doing a data sanity check before
     * doing something unrecoverable such as a dropTable.
     * Since 1.7
     *
     * Not supported with Formatted Mongo.
     */
    val preConditions: List<Any>? = null,
    /**
     * Specifies SQL statements or Change Type tags that describe how to rollback the changeset.
     * For more information, see Liquibase Rollback Workflow and Automatic and Custom Rollbacks.
     */
    val rollback: List<Any>? = null,
    /**
     * Liquibase Pro 4.26.0+.
     * Formatted SQL only.
     * Lets you specify a SQL file to roll back rather than an inline SQL statement.
     * For more information, see Example Changelogs: SQL Format.
     */
    val rollbackSqlFile: String? = null,
    /**
     * Specifies the description of the changeset. XML comments provide the same benefit.
     */
    val comment: String? = null,
    /**
     * Adds a checksum that is considered valid for this changeset, regardless of what is stored in the database.
     * It is primarily used when you need to change a changeset and don't want errors thrown on databases on
     * which it has already been run (not a recommended procedure). Special value "1:any" will match to
     * any checksum and will not execute the changeset on ANY change. Since 1.7
     */
    val validCheckSum: String? = null
)